
# env = dev | stage | uat
env=dev

browser=chrome
run_in_maximised_mode=true
implicit_wait_duration_seconds=5

dev_base_url=https://practicesoftwaretesting.com
dev_admin_email=richard-dev@gmail.com
dev_admin_password=pass@123

stage_base_url=https://stage.practicesoftwaretesting.com
stage_admin_email=richard-stage@gmail.com
stage_admin_password=pass@123

uat_base_url=https://uat.practicesoftwaretesting.com
uat_admin_email=richard-uat@gmail.com
uat_admin_password=pass@123